### ISSUE TITLE
Pre-publish Todo's

### ISSUE THREAD

**Issue by dustin-H** [dustin-H/bauhaus-ui#90]
- [x] Clean up old files
- [x] Docs for singlePageView
- [x] Docs for InputSelect multiple option
- [x] Update external module docs (__GLOBAL__.exportDefault isn't required anymore)
- [x] Remove unnecessary console.log()'s
- [x] Update Readme
- [x] Ensure full docs
- [x] Create demo-repo
- [x] Ensure i18n fallbacks are really working... had some problems with them
